### ISSUE TITLE
Preparing for Gramps 5.2

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#424]
When Gramps 5.2 is released, I assume we will follow by releasing a new version (1.2 or 2.0?) that is compatible _only_ with Gramps 5.2.

Let's use this issue to list what changes are required.

Personally, I haven't started playing with 5.2 beta yet.

**Comment by emyoulation** [comment]
I am curious about the edfect of different version of Gramps with the sync.

What happens when a 5.2 user enters the new Superscript or Subscript type styling in a Note and tries to sync to a 5.1 GrampsWeb? And if that is successful, what haopens when a 5.1 user tries to sync to 5.2 data?

The example.gramps is in the process of being updated for examples of 5.2 data. Maybe be it would be a good tree to serve with GrampsWeb?

**Comment by DavidMStraub** [comment]
I think it would make sense to require MAJOR.MINOR to match between client and server and otherwise to abort.

**Comment by DavidMStraub** [comment]
@Nick-Hall can you please ping in this issue some time ahead of a final 5.2 release? I would like to make the Web API release based on 5.2 almost simultaneously to give users the option to upgrade at the same time.

**Comment by DavidMStraub** [comment]
Added a new branch `2.0` for the future Web API 2.0 release based on Gramps 5.2. Not many changes are needed, but a major version bump is necessary because the Gramps database schema changed.

**Comment by DavidMStraub** [comment]
@Nick-Hall congrats on releasing 5.2 :tada:

How do you plan to proceed with the PyPI release in the near term so we can update the installation method for Web API 2.0 accordingly?

A possible fallback would be to use git+https for the released tag, similar to what we do now for the tests on the 2.0 branch

https://github.com/gramps-project/gramps-web-api/blob/2.0/.github/workflows/test.yml#L20

but that wouldn't be optimal of course.

**Comment by Nick-Hall** [comment]
I don't see the "gramps" project name being released to us quickly.  There is another project that had their request authorised on 18th Dec 2023, but the name still hasn't been transferred.

We could choose another name such as gramps-gui, gramps-desktop or gramps-full.  I'd like to use gramps-core and gramps-cli for cut-down versions in the future.

Your fallback option also sounds reasonable to me.

**Comment by emyoulation** [comment]
gramps-desktop makes sense to me... since "Gramps for desktops" is already starting to creep into our conversations online. 
And it leaves room for "mobile" and "vr" distinctions within a "gui" classification.

 
  On Sun, Feb 25, 2024 at 4:15 PM, Nick ***@***.***> wrote:   


I don't see the "gramps" project name being released to us quickly. There is another project that had their request authorised on 18th Dec 2023, but the name still hasn't been transferred.

We could choose another name such as gramps-gui, gramps-desktop or gramps-full. I'd like to use gramps-core and gramps-cli for cut-down versions in the future.

Your fallback option also sounds reasonable to me.

**Comment by Nick-Hall** [comment]
OK.  I've uploaded it to gramps-desktop and created a couple of placeholders for gramps-gtk and gramsp-gui.

https://pypi.org/project/gramps-desktop/

**Comment by emyoulation** [comment]
The descriptions for gramps-gui and gramps-gtk say they are for addons.

![Screenshot_20240225_184310_Chrome.jpg](https://github.com/gramps-project/gramps-web-api/assets/69127217/8ec259ac-7f81-42d7-9031-813bb714ca0c)

A search for Gramps shows quite an assortment. (Since "glab" is Doug Blank's Jupyter flavor, perhaps he ought to be drawn into the conversation?)

Search PyPI for Gramps and python :
https://pypi.org/search/?q=gramps&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3

**Comment by emyoulation** [comment]
The descriptions for gramps-gui and gramps-gtk say they are for addons.

![Screenshot_20240225_184310_Chrome.jpg](https://github.com/gramps-project/gramps-web-api/assets/69127217/8ec259ac-7f81-42d7-9031-813bb714ca0c)

A search for Gramps shows quite an assortment. (Since "glab" is Doug Blank's Jupyter flavor, perhaps he ought to be drawn into the conversation?)

Search PyPI for Gramps and python :
https://pypi.org/search/?q=gramps&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3

**Comment by DavidMStraub** [comment]
Just upgraded my own trees to Gramps 5.2.0 and Web API 2.0, so far everything running nice & smooth including sync!
