### ISSUE TITLE
Allow associating zipped media files with media objects imported from GEDCOM by file name

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-web-api#441]
I imported a GEDCOM file together with a zipped file with some media, but they are not linked to the persons or events (empty gallery tab).

```
0 @M14@ OBJE
1 FILE hartenthaler_helmut.jpg
2 FORM jpeg
3 TYPE photo
2 TITL Helmut Hartenthaler
1 SOUR @S6@
1 CHAN
2 DATE 10 JUN 2012
3 TIME 23:17:03
``` 

The error message is:
```
Could not import hartenthaler_helmut.jpg Line 226519: 1 FILE hartenthaler_helmut.jpg
```

Adding a single image to a person is no problem.

**Comment by DavidMStraub** [comment]
Indeed, unfortunately it is not possible to import GEDCOM files with media and then associate the media files afterwards. This is because associating files by path, as is done in Gramps desktop, is difficult to implement without running into security issues on a server. This is why Gramps Web currently only allows associating media files by their Checksums.

Importing an existing GEDCOM files thus requires importing it locally into Gramps desktop, making sure Gramps Desktop has found all the files and calculated the checksums, and then exporting a Gramps XML.

Please have a look at the documentation at https://www.grampsweb.org/user-guide/import/ and feel free to suggest improvements to this documentation, it might not be very clear.

We can also think about actually making this possible, but it's tricky.

By the way, I also wrote a blog article last weekend describing first steps and media upload (in German): https://www.grampshub.com/blog/de/2023/10/28/erste-schritte-mit-gramps-web.html

**Comment by hartenthaler** [comment]
Vielen Dank für Deine Links. Damit verstehe ich es. Aber ich finde diesen Weg über das Desktop-Programm sehr umständlich. Warum muss die Verknüpfung über eine Prüfsumme erfolgen anstatt den Dateinamen dafür zu verwenden? Im OBJE Datensatz steht der Dateiname und in der Zip-Datei mit den Medien doch auch. Damit ist doch klar was zusammen gehört. Und wenn ich an GEDCOM 7 denke mit dem dort spezifizieren zip-Format, ist doch klar wie das zukünftig gelöst werden muß.

**Comment by hartenthaler** [comment]
Ich bin zwar mit Handbüchern groß geworden, habe 1.000 Seiten Word, Excel, von vorne bis hinten gelesen. Aber dass ich heutzutage eine Anleitung lesen muss, um eine GEDCOM Datei mit Mediendateien zu importieren, finde ich unzumutbar.

**Comment by DavidMStraub** [comment]
Ja, das ist was dran ... ich ändere jedenfalls mal die Kategorie in "enhancement".

**Comment by DavidMStraub** [comment]
Implementation note:

Currently zipped media files are associated with media objects only by checksum, since incorrect checksums break Gramps Web.

However, media objects imported from GEDCOM on Gramps Web do not have any checksum. So in a second pass after associating the ones with checksums, we could try associating the objects *without* checksum by filename, and update the media objects.
