### ISSUE TITLE
How to connect to a Postgres database

### ISSUE THREAD

**Issue by mmomjian** [gramps-project/gramps-web-api#455]
I am struggling to connect GrampsWeb to a postgresql database running on the same server. I have tried following the [instructions](https://www.grampsweb.org/Postgres/), but the Configuration section doesn't seem to specify at all how to enter the connection / location of the database. The instructions also refer to variables like POSTGRES_USER and POSTGRES_PASSWORD, but when I use these I get an error in the logs stating this is deprecated and to use GRAMPSWEB_POSTGRES_xx. I at some point found the configuration variable GRAMPSWEB_USER_DB_URI [source](https://www.grampsweb.org/Configuration/), and using postgresql://user:pw@ip/database for this seems to allow a connection to PG.

The main issue now is that my grampsweb logs are now full of errors like `Unable to init server: Could not connect: Connection refused`. The postgres logs have errors from the gramps user stating `LOG:  could not receive data from client: Connection reset by peer`. So I think it is able to connect, but it doesn't seem to be working. Does anyone have a working postgres + grampsweb install? I use the same PG server for a bunch of other services so I believe it is configured properly.

**Comment by DavidMStraub** [comment]
Hi, can you elaborate on the setup you are trying to achieve? In particular, are you setting up a single-tree or multi-tree deployment? It makes quite a big difference.

**Comment by mmomjian** [comment]
Thanks for the reply. I was trying to use single-tree, with the following settings:
```GRAMPSWEB_TREE: 'gramps_user'
GRAMPSWEB_POSTGRES_USER: 'gramps_user'
GRAMPSWEB_POSTGRES_PASSWORD: 'redacted'
GRAMPSWEB_USER_DB_URI: 'postgresql://gramps_user:redacted@ip:port/gramps_user'```

I have also tried with `GRAMPSWEB_TREE: 'postgres'` and the errors about "connection reset" seem to persist. Happy to provide any info needed any hopefully help improve the documentation of this feature.

**Comment by DavidMStraub** [comment]
Hi,

`NEW_DB_BACKEND` is only relevant for the multi-tree setup (when creating a new tree via the API).

In the single-tree setup, creating a non-existing database automatically is only done for SQLite. For Postgres, that doesn't make much sense (IMO) because you anyway need to set up the database in advance.

So the database needs to be prepared using the [usual instructions](https://gramps-project.org/wiki/index.php/PostgreSQL) and then the Gramps tree created using the [Gramps CLI](https://gramps-project.org/wiki/index.php/Gramps_5.1_Wiki_Manual_-_Command_Line).

**Comment by DavidMStraub** [comment]
I extended the docs. It would still be good to have a full docker-compose example, but I'll close this one for now.
