### ISSUE TITLE
Error 500 "file not found"  when syncing image filename begins with a number

### ISSUE THREAD

**Issue by tkyler** [gramps-project/gramps-web-api#550]
I had an image named "2200_blahblah.png" and it would not sync, resulting in "Error 500" and the following, but the file exists.  I changed the name of the file so as to begin with a char and it sync'd fine.  FWIW.  

![image](https://github.com/user-attachments/assets/3aa50360-ce25-4cd2-a90d-fdbf381edf19)

**Comment by DavidMStraub** [comment]
Hi @tkyler, the error message you posted is realted to the Gramps Web Sync Addon, I will shift the issue there.

But the traceback clearly shows that Python raises a `FileNotFoundError` on this path, so it can't have anything to do with the file name. I suspect it's because the folder `/User/tkyler/Desktop/gramps_media/` did not exist and the code tried to write the file without creating the folder first. Can you confirm that's possible?

**Comment by DavidMStraub** [comment]
Sorry, I realized I can't transfer this issue to https://github.com/DavidMStraub/gramps-web-sync as they are in two different Github orgs, please feel free to open a new issue there. It would be valuable to know whether the problem could have been caused by the missing directory.
