### ISSUE TITLE
Connection leaks when using PostgreSQL

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#552]
I am observing connection leaks (database connections not closed properly) when using PostgreSQL as backend (SharedPostgreSQL, search index,  transaction history). This can lead to the database rejecting connection attempts.

**Comment by MrTrustor** [comment]
I'm observing the same thing, but with the PostgreSQL AddOn. Even when grampsweb just started (and so there are still some connections available), the performance is really poor with a very small database (less than 40 people).

I've installed pgbouncer to mitigate the issue a little bit, but after after a few minutes of usage (adding new individuals, families, events, etc.), I reached the default 120 connections from grampsweb to pgbouncer.

**Comment by DavidMStraub** [comment]
Thanks for sharing, I was also about to install pgbouncer for mitigation, so you're saying it doens't help?

For me, setting max connections to 200 and the idle timeouts to 15 minutes seems to work kind of ok for now, but it's not a proper solution.

Are you using Postgres also for the search index and the user database or only for the tree?

**Comment by MrTrustor** [comment]
I'm also using Pg for the user database and the index. The user database does not seem to be the issue, as I have a different Pg user for that and I can see that the number of connections for that user remains low.

pgbouncer does help because it can handle many more connections. I increased the max_client_conn to 200+ and set a client idle timeout to prune old connections. It's not perfect, because sometimes that timeout will prune valid connections. But at least, it makes the whole thing limp along and not get completely locked up.

**Comment by MrTrustor** [comment]
A few more notes on the behavior I'm seeing (with pgbouncer):
* Read-only actions seem to be mostly fine and responsive
* Create/update actions are very sluggish. Typically my reverse proxy times out before sending back a response to PUT requests.
* When I create an object from another one (e.g creating and linking a note directly from an individual), the creation happens, but not the linking (maybe because my reverse proxy times out before the frontend can do the linking?): I have to reload the page, and manually link the new object to my individual/family/whatever.

It _feels_ like I didn't have these issues when I was running the Gramps Web docker image for 24.7, but that might be a red herring.

**Comment by DavidMStraub** [comment]
Thanks, very useful observations. The two most likely culprits based on these observations are the search index (which is in the same database and is updated on every edit) and the transaction history (same). Whether it's the search index you could check relatively easily by temporarily switching to SQLite for the index.

**Comment by MrTrustor** [comment]
I just tried switching the search index back to SQLite, and triggered a reindexing. It seems a bit better, but it's still not great. That may be because the search index is not being slowed down by whatever is the problem (transaction history?) anymore.

**Comment by DavidMStraub** [comment]
I am wondering whether the problem is the engine created for the undo DB here

https://github.com/gramps-project/gramps-web-api/blob/master/gramps_webapi/undodb.py#L182

and whether calling `engine.dispose()` in the flask app teardown callback could help...

**Comment by DavidMStraub** [comment]
After deploying v2.4.3 on October 9, I have seen the number of connections going back to normal levels, so it seems that indeed the problem is solved! @MrTrustor would be interested if it works better for you as well.

![grafik](https://github.com/user-attachments/assets/19d1d87d-c658-42ff-9e7c-efe798613068)

**Comment by DavidMStraub** [comment]
Good point, just triggered a new image build, you can use `latest-devel` now.

**Comment by MrTrustor** [comment]
Thanks. I've deployed it, it runs. I'll probably test things a bit more in depth over the week-end.

**Comment by MrTrustor** [comment]
I've played around with the patched version a bit. It does seem to solve the connection leak problem: I was able to remove the client idle timeout from pgbouncer, and the whole thing works.

_However_, the create/update actions are still very slow: creating a new person easily takes 10-15s. Assigning a person to a face on a picture, around the same time, etc.

Granted, I don't have the fastest database ever (my Postgres instance runs on a NAS with hard drives, no SSD), and I haven't assigned a _lot_ of resources to Gramps or Celery (2 CPUs, 4 GB of RAM each), but still: I would expect faster response times than that.

How can I help debug that slowness? Should I open a new bug for that?

**Comment by DavidMStraub** [comment]
Great to hear the connection leak is solved.

Concerning slowness: yes, let's try to figure out what the problem is. Perhaps in a Github discussion or a forum post? We will need to look at your full compose YAML (with secrets redaced obviously).
