### ISSUE TITLE
Gramps Web demo “Add button” feature missing for “Contributor”

### ISSUE THREAD

**Issue by emyoulation** [gramps-project/gramps-web-api#559]
The blue "Add" button is missing from the lower right of the Family and Media lists when using the Contributor login for the [Gramps Web demo](https://www.grampsweb.org/). That button exists for Contributor in the all the other views. (Workaround: The add menu allows Family and Media object adding for Contributors.)

When logged in as Owner or Editor, the button is shown as expected.

Note that the Demo was reporting 422 errors when searching the Views. Logging out and back in resolved.

**Comment by DavidMStraub** [comment]
Yes, actually contributors cannot add media or families at the moment unfortunately. The reason is that contributors have permissions to *add but not edit* primary Gramps objects, and due to the way Gramps is set up, adding a family always requires editing the people that make up the family (by modifying their `family_list` or `parent_family_list`. For media obejcts, it's a bit more subtle; in reality, there are two separate underlying actions, uploading the media file and adding the media metadata (title, date etc.). The backend creates a media file and an associated media object, and then in a second step modifies this media object with the metadata.

Of course those backend limitations don't make sense from a user point of view, so it should be fixed, but it's difficult.
